CREATE DATABASE IF NOT EXISTS judge;

CREATE USER IF NOT EXISTS "webapp"@"%" IDENTIFIED BY "webapp";
GRANT ALL PRIVILEGES ON judge.* TO "webapp"@"%";

CREATE USER IF NOT EXISTS "worker"@"%" IDENTIFIED BY "worker";
GRANT SELECT, INSERT, UPDATE, DELETE ON judge.* TO "worker"@"%";

FLUSH PRIVILEGES;
