variables:
  CI_REGISTRY: reg.nju.edu.cn
  ENV_IMAGE: reg.nju.edu.cn/psv/dotoj/env
  WEBAPP_IMAGE: reg.nju.edu.cn/psv/dotoj/webapp
  WORKER_IMAGE: reg.nju.edu.cn/psv/dotoj/worker

stages:
  - env
  - build
  - release

.docker_login: &docker-login
  before_script:
    - chmod +x ./release.sh
    - echo "${CI_REGISTRY_PASS}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}

env:docker:
  only:
    - tags
  stage: env
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:dind
  <<: *docker-login
  script:
    - ./release.sh env ${ENV_IMAGE} latest

build:webapp:
  only:
    - tags
  stage: build
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:dind
  <<: *docker-login
  script:
    - ./release.sh webapp ${WEBAPP_IMAGE} development-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA} ${CI_COMMIT_TAG}

build:worker:
  only:
    - tags
  stage: build
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:dind
  <<: *docker-login
  script:
    - ./release.sh worker ${WORKER_IMAGE} development-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA} ${CI_COMMIT_TAG:1}

release:package:
  only:
    - tags
  when: manual
  stage: release
  image: alpine:latest
  before_script:
    - chmod +x ./release.sh
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.nju.edu.cn/g' /etc/apk/repositories
    - apk add zip
  script:
    - ./release.sh package release.zip development-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA} ${CI_COMMIT_TAG:1}
  artifacts:
    paths:
      - ./release.zip
