FROM reg.nju.edu.cn/psv/dotoj/sdk:6.0
WORKDIR /app

WORKDIR /src
COPY ./*.sln ./
COPY Client/*.mdproj Client/
COPY Notification/*.csproj Notification/
COPY Server/*.csproj Server/
COPY Shared/*.csproj Shared/
COPY Worker/*.csproj Worker/
RUN dotnet restore -s https://mirrors.cloud.tencent.com/nuget/

COPY . ./

