FROM ccr.ccs.tencentyun.com/dotoj/sdk:5.0
WORKDIR /app

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list

WORKDIR /src
COPY ./*.sln ./
COPY Data/*.csproj Data/
COPY Notification/*.csproj Notification/
COPY WebApp/*.csproj WebApp/
COPY Worker/*.csproj Worker/
RUN dotnet restore

COPY . ./

