FROM mcr.microsoft.com/dotnet/aspnet:6.0

RUN sed -i -E 's/http(s)?:\/\/deb.debian.org/https:\/\/mirrors.nju.edu.cn/' /etc/apt/sources.list
RUN sed -i -E 's/http(s)?:\/\/security.debian.org/https:\/\/mirrors.nju.edu.cn/' /etc/apt/sources.list

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
RUN apt update -yqq
RUN apt-get update -yqq
