IF SUSER_ID(N'judge1') IS NOT NULL
BEGIN
    SET NOEXEC ON;
END
CREATE LOGIN judge1 WITH PASSWORD = N'judge1',
    CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
CREATE USER judge1 FOR LOGIN judge1;
CREATE DATABASE judge1;
ALTER AUTHORIZATION ON DATABASE::judge1 TO judge1;
SET NOEXEC OFF;

IF SUSER_ID(N'hangfire') IS NOT NULL
BEGIN
    SET NOEXEC ON;
END
CREATE LOGIN hangfire WITH PASSWORD = N'hangfire',
    CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
CREATE USER hangfire FOR LOGIN hangfire;
CREATE DATABASE hangfire;
ALTER AUTHORIZATION ON DATABASE::hangfire TO hangfire;
SET NOEXEC OFF;
