version: '3.8'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  caddy:
    driver: ${VOLUMES_DRIVER}
  mssql:
    driver: ${VOLUMES_DRIVER}
  judge1:
    driver: ${VOLUMES_DRIVER}

services:
  caddy:
    build:
      context: ./caddy
    volumes:
      - ./caddy:/etc/caddy
      - ${DATA_PATH_HOST}/caddy:/data
    ports:
      - "${CADDY_HTTP_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"
      - "${CADDY_ADMIN_PORT}:2019"
    networks:
      - frontend
      - backend

  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
      - backend
  
  web:
    build:
      context: ./web
    volumes:
      - ./web/identity.pfx:/app/identity.pfx
      - ./web/appsettings.json:/app/appsettings.json
    networks:
      - backend
    