version: '2'

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  caddy:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  rabbitmq:
    driver: ${VOLUMES_DRIVER}
  webapp:
    driver: ${VOLUMES_DRIVER}
  worker:
    driver: ${VOLUMES_DRIVER}

services:
  caddy:
    image: caddy:2-alpine
    volumes:
      - ./caddy:/etc/caddy
      - ${DATA_PATH_HOST}/caddy:/data
      - ${DATA_PATH_HOST}/static:/var/www/static:ro
    <<: *default-logging
    ports:
      - "${CADDY_HTTP_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"
      - "${CADDY_ADMIN_PORT}:2019"
    networks:
      - frontend
      - backend

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    <<: *default-logging
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
      - backend
        
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    <<: *default-logging
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - backend

  webapp:
    image: ccr.ccs.tencentyun.com/dotoj/webapp:${WEBAPP_VERSION}
    volumes:
      - ./webapp/identity.pfx:/app/identity.pfx:ro
      - ./webapp/appsettings.json:/app/appsettings.json:ro
      - ${DATA_PATH_HOST}/aspnet:/root/.aspnet
      - ${DATA_PATH_HOST}/static:/app/wwwroot/static
      - ${DATA_PATH_HOST}/data/tests:/data/tests
      - ${DATA_PATH_HOST}/data/submissions:/data/submissions
      - ${DATA_PATH_HOST}/data/plagiarisms:/data/plagiarisms
    <<: *default-logging
    networks:
      - backend

  worker:
    image: ccr.ccs.tencentyun.com/dotoj/worker:${WORKER_VERSION}
    privileged: true
    mem_swappiness: 0
    volumes:
      - ./worker/appsettings.json:/app/appsettings.json:ro
      - ${DATA_PATH_HOST}/data/tests:/data/tests:ro
      - ${DATA_PATH_HOST}/data/submissions:/data/submissions:ro
      - ${DATA_PATH_HOST}/data/plagiarisms:/data/plagiarisms
    <<: *default-logging
    networks:
      - backend
