version: '2'

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  caddy:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  webapp:
    driver: ${VOLUMES_DRIVER}
  worker:
    driver: ${VOLUMES_DRIVER}

services:
  caddy:
    build:
      context: ./caddy
    volumes:
      - ./caddy:/etc/caddy
      - ${DATA_PATH_HOST}/caddy:/data
    <<: *default-logging
    ports:
      - "${CADDY_HTTP_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"
      - "${CADDY_ADMIN_PORT}:2019"
    networks:
      - frontend
      - backend

  webapp:
    image: ccr.ccs.tencentyun.com/dotoj/webapp:${WEBAPP_VERSION}
    volumes:
      - ./webapp/identity.pfx:/app/identity.pfx:ro
      - ./webapp/appsettings.json:/app/appsettings.json:ro
      - ${DATA_PATH_HOST}/aspnet:/root/.aspnet
      - ${DATA_PATH_HOST}/static:/app/wwwroot/static
      - ${DATA_PATH_HOST}/judge-data:/var/www/judge-data
    <<: *default-logging
    networks:
      - backend

  worker:
    image: ccr.ccs.tencentyun.com/dotoj/worker:${WORKER_VERSION}
    privileged: true
    mem_swappiness: 0
    volumes:
      - ./worker/appsettings.json:/app/appsettings.json:ro
      - ${DATA_PATH_HOST}/judge-data:/var/www/judge-data:ro
    <<: *default-logging
    networks:
      - backend

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    <<: *default-logging
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
      - backend
