name: build-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Extract tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Restore nuget packages
        run: dotnet restore
      - name: Build webapp
        run: |
          dotnet publish Server -c Release -o /tmp/Webapp
          tar czf webapp-${{ env.TAG }}-linux-amd64.tar.gz -C /tmp Webapp
      - name: Build worker
        run: |
          dotnet publish Worker -c Release -o /tmp/Worker
          tar czf worker-${{ env.TAG }}-linux-amd64.tar.gz -C /tmp Worker
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            webapp-${{ env.TAG }}-linux-amd64.tar.gz
            worker-${{ env.TAG }}-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
